name: Birthday Bot

on:
  schedule:
    # Har kuni 09:15 Toshkent vaqti → UTC 04:15
    - cron: "15 4 * * *"
  workflow_dispatch:  # Qo‘lda ham ishga tushirish mumkin

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutubxonalarni o'rnatish
        run: |
          pip install --upgrade pip
          pip install pandas python-telegram-bot==20.3 pytz

      - name: Botni ishga tushirish
        run: python bot.py
