name: Birthday Bot

on:
  schedule:
    - cron: "25 3 * * *"   # UTC 03:25 = Toshkent 08:25
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kerakli kutubxonalarni o'rnatish
        run: |
          pip install --upgrade pip
          pip install pandas python-telegram-bot==20.3

      - name: Botni ishga tushirish
        run: python bot.py
