name: Birthday Bot

on:
  schedule:
    # Har kuni 03:00 UTC → Toshkent vaqti 08:00
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repositoryni klonlash
      - uses: actions/checkout@v4

      # 2️⃣ Python o'rnatish
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Kerakli kutubxonalarni o'rnatish
      - run: pip install pandas python-telegram-bot

      # 4️⃣ Botni ishga tushirish
      - run: python bot.py
